### ISSUE TITLE
Debugger Package

### ISSUE THREAD

**Issue by philippvr** [steelbrain/debugger#2]
Hi,
I've also been working on a [generic debugger](https://github.com/philippvr/debugger) package for atom these days. It's far from finished but has some things working like
- Adding/removing breakpoints
- Stepping
- Printing the call stack and local variables

I've started implementing a [debugger that works with gdb/lldb](https://github.com/philippvr/debugger-mi2), but it should also work with the node debugger and others.

Maybe we could join the efforts. Are you interested?

Best, Philipp

**Comment by steelbrain** [comment]
We are definitely interested in joining efforts but there are a few things we would have to discuss before we do. Are you on Atom slack?

**Comment by philippvr** [comment]
I've registered and am online.
